# This is the configuration for a Netlify environment using Netlify Identity and Git Gateway.
backend:
  name: git-gateway # Tells the CMS to use Netlify's Git Gateway service
  branch: main # IMPORTANT: Change this to 'master' if that is your default branch

# Where to store media files (images, PDFs) that you upload through the CMS.
# The 'assets' folder is the modern standard for Hugo.
media_folder: "assets/media/"
public_folder: "/media/"

# The collections are the heart of the CMS. Each collection represents a type of content.
collections:
  # COLLECTION 1: Site-wide settings and your main profile.
  # This is a "File Collection", meaning it edits specific, single files.
  - name: "settings"
    label: "Site Settings & Profile"
    files:
      # File 1.1: Your main user profile
      - file: "content/authors/admin/_index.md"
        label: "My Profile"
        name: "profile"
        fields:
          - {label: "Title (Your Name)", name: "title", widget: "string"}
          - {label: "Is this the main user?", name: "superuser", widget: "boolean", default: true}
          - {label: "Role", name: "role", widget: "string"}
          - {label: "Organizations", name: "organizations", widget: "list", fields: [{label: Name, name: name, widget: string}, {label: URL, name: url, widget: string}]}
          - {label: "Short Biography", name: "bio", widget: "text"}
          - {label: "Interests", name: "interests", widget: "list"}
          - {label: "Education (Courses)", name: "education", widget: "object", fields: [{label: Courses, name: courses, widget: list, fields: [{label: Course Name, name: course, widget: string}, {label: Institution, name: institution, widget: string}, {label: Year, name: year, widget: number}]}]}
          - {label: "Social Media & Other Links", name: "social", widget: "list", fields: [{label: Icon, name: icon, widget: string, hint: "E.g., 'envelope', 'twitter', 'github'. See Font Awesome docs."}, {label: Icon Pack, name: "icon_pack", widget: "string", hint: "E.g., 'fas', 'fab'"}, {label: Link, name: link, widget: string}]}
          - {label: "Email for Contact Form", name: "email", widget: "string"}

      # File 1.2: The main navigation menu
      - file: "config/_default/menus.yaml"
        label: "Navigation Menu"
        name: "menu"
        fields:
          - name: main
            label: Menu Items
            widget: list
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
              - {label: "Order (Weight)", name: "weight", widget: "number"}

      # File 1.3: Theme-wide parameters
      - file: "config/_default/params.yaml"
        label: "Theme & Site Parameters"
        name: "params"
        fields:
          - {label: "Theme", name: "theme", widget: "select", options: ["minimal", "classic", "ocean", "forest", "dark", "mr-robot", "custom"]}
          - {label: "Font", name: "font", widget: "select", options: ["default", "classic", "rose", "ocean"]}
          - {label: "Show 'Published with' footer?", name: "power_by", widget: "boolean", default: true}
          - {label: "Show Copyright notice?", name: "copyright_license", widget: "object", fields: [{label: Enable?, name: enable, widget: boolean}, {label: License, name: license, widget: select, options: ["cc-by-sa-4.0", "cc-by-4.0", "cc-by-nd-4.0", "cc-by-nc-4.0", "cc-by-nc-nd-4.0", "cc-by-nc-sa-4.0"]}, {label: Notice, name: notice, widget: string, required: false}]}

  # COLLECTION 2: The sections on your homepage.
  # Also a "File Collection".
  - name: "home"
    label: "Homepage Sections"
    files:
      - file: "content/home/about.md"
        label: "About Me (Biography)"
        name: "about"
        fields:
          - {label: "Enable?", name: "active", widget: "boolean", default: true}
          - {label: "Order (Weight)", name: "weight", widget: "number"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "content/home/skills.md"
        label: "Skills"
        name: "skills"
        fields:
          - {label: "Enable?", name: "active", widget: "boolean", default: true}
          - {label: "Order (Weight)", name: "weight", widget: "number"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "content/home/experience.md"
        label: "Experience"
        name: "experience"
        fields:
          - {label: "Enable?", name: "active", widget: "boolean", default: true}
          - {label: "Order (Weight)", name: "weight", widget: "number"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "content/home/accomplishments.md"
        label: "Accomplishments"
        name: "accomplishments"
        fields:
          - {label: "Enable?", name: "active", widget: "boolean", default: true}
          - {label: "Order (Weight)", name: "weight", widget: "number"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "content/home/posts.md"
        label: "Recent Posts"
        name: "posts"
        fields:
          - {label: "Enable?", name: "active", widget: "boolean", default: true}
          - {label: "Order (Weight)", name: "weight", widget: "number"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "content/home/contact.md"
        label: "Contact"
        name: "contact"
        fields:
          - {label: "Enable?", name: "active", widget: "boolean", default: true}
          - {label: "Order (Weight)", name: "weight", widget: "number"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

  # COLLECTION 3: Blog Posts
  # This is a "Folder Collection" where you can create new files.
  - name: "posts"
    label: "Blog Posts"
    folder: "content/post/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Authors", name: "authors", widget: "list", default: ["admin"]}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Summary", name: "summary", widget: "text"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  # COLLECTION 4: Publications
  - name: "publications"
    label: "Publications"
    folder: "content/publication/"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Authors", name: "authors", widget: "list"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Publication Venue", name: "publication", widget: "string"}
      - {label: "Publication Venue (Short)", name: "publication_short", widget: "string"}
      - {label: "Abstract", name: "abstract", widget: "markdown"}
      - {label: "Featured?", name: "featured", widget: "boolean", default: false}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "URL to PDF", name: "url_pdf", widget: "string", required: false}
      - {label: "URL to Code", name: "url_code", widget: "string", required: false}
      - {label: "URL to Dataset", name: "url_dataset", widget: "string", required: false}
      - {label: "URL to Project Page", name: "url_project", widget: "string", required: false}
      - {label: "URL to Slides", name: "url_slides", widget: "string", required: false}
      - {label: "URL to Video", name: "url_video", widget: "string", required: false}

  # COLLECTION 5: Talks
  - name: "talks"
    label: "Talks & Events"
    folder: "content/event/"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Summary", name: "summary", widget: "text"}
      - {label: "Abstract", name: "abstract", widget: "markdown"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "URL to Slides", name: "url_slides", widget: "string", required: false}
      - {label: "URL to Video", name: "url_video", widget: "string", required: false}