backend:
  name: github # This will be ensured by the JS above anyway
  repo: bhati-saa/bhati-saa.github.io # YOUR REPO
  branch: main # YOUR BRANCH
  # auth_type: github # Ensured by JS

media_folder: "static/uploads_test" # Simple path, ensure this folder can be created or exists
public_folder: "/uploads_test"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts_test" # Use a test folder
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}