# Backend configuration for Netlify Identity and Git Gateway
backend:
  name: git-gateway
  branch: main # IMPORTANT: Change to 'master' if your branch is named master

# Media files will be stored in the 'assets' folder, which is the Hugo standard.
media_folder: "assets/media/"
public_folder: "/media/"

# The collections that define the editable content of your site.
collections:
  # COLLECTION 1: Your main author profile. This is the most important section.
  - name: "profile"
    label: "My Profile"
    files:
      - file: "content/authors/admin/_index.md"
        label: "Author Profile"
        name: "author_profile"
        fields:
          - {label: "Is this the main user?", name: "superuser", widget: "boolean", default: true}
          - {label: "Your Name", name: "title", widget: "string"}
          - {label: "Role / Job Title", name: "role", widget: "string", required: false}
          - {label: "Organizations", name: "organizations", widget: "list", required: false, fields: [{label: Name, name: name, widget: string}, {label: URL, name: url, widget: string, required: false}]}
          - {label: "Interests", name: "interests", widget: "list", required: false}
          - label: "Education"
            name: "education"
            widget: "object"
            fields:
              - name: "courses"
                label: "Degrees & Courses"
                widget: "list"
                required: false # This allows the list to be empty
                fields:
                  - {label: "Course / Degree", name: "course", widget: "string", required: false}
                  - {label: "Institution", name: "institution", widget: "string", required: false}
                  - {label: "Year", name: "year", widget: "number", required: false}
          - {label: "Social Media & Other Links", name: "social", widget: "list", required: false, fields: [{label: Icon, name: icon, widget: string, hint: "E.g., 'envelope', 'twitter', 'github'. See Font Awesome docs."}, {label: Icon Pack, name: "icon_pack", widget: "string", hint: "E.g., 'fas', 'fab'"}, {label: Link, name: link, widget: string}]}
          - {label: "Email for Contact Form", name: "email", widget: "string", required: false}
          - {label: "Main Biography Content", name: "body", widget: "markdown", hint: "This is the main text that appears in your 'About Me' section."}

  # COLLECTION 2: The sections on your homepage.
  - name: "home"
    label: "Homepage Sections"
    files:
      - file: "content/home/about.md"
        label: "About (Biography)"
        name: "home_about"
        fields:
          - {label: "Enable this section?", name: "active", widget: "boolean", default: true}
          - {label: "Order (Weight)", name: "weight", widget: "number", default: 10, hint: "Lower numbers appear higher on the page."}
          - {label: "Title", name: "title", widget: "string", required: false, hint: "Leave blank to use default. This section displays your main profile."}
      - file: "content/home/skills.md"
        label: "Skills"
        name: "home_skills"
        fields:
          - {label: "Enable this section?", name: "active", widget: "boolean", default: true}
          - {label: "Order (Weight)", name: "weight", widget: "number", default: 20}
          - {label: "Title", name: "title", widget: "string", default: "Skills"}
          - {label: "Body (Content)", name: "body", widget: "markdown"}
      - file: "content/home/experience.md"
        label: "Experience"
        name: "home_experience"
        fields:
          - {label: "Enable this section?", name: "active", widget: "boolean", default: true}
          - {label: "Order (Weight)", name: "weight", widget: "number", default: 30}
          - {label: "Title", name: "title", widget: "string", default: "Experience"}
          - {label: "Body (Content)", name: "body", widget: "markdown"}
      - file: "content/home/accomplishments.md"
        label: "Accomplishments"
        name: "home_accomplishments"
        fields:
          - {label: "Enable this section?", name: "active", widget: "boolean", default: true}
          - {label: "Order (Weight)", name: "weight", widget: "number", default: 40}
          - {label: "Title", name: "title", widget: "string", default: "Accomplishments"}
          - {label: "Body (Content)", name: "body", widget: "markdown"}
      - file: "content/home/posts.md"
        label: "Recent Posts"
        name: "home_posts"
        fields:
          - {label: "Enable this section?", name: "active", widget: "boolean", default: true}
          - {label: "Order (Weight)", name: "weight", widget: "number", default: 50}
          - {label: "Title", name: "title", widget: "string", default: "Recent Posts"}
          - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
          - {label: "Number of posts to show", name: "count", widget: "number", default: 3}
      - file: "content/home/contact.md"
        label: "Contact"
        name: "home_contact"
        fields:
          - {label: "Enable this section?", name: "active", widget: "boolean", default: true}
          - {label: "Order (Weight)", name: "weight", widget: "number", default: 60}
          - {label: "Title", name: "title", widget: "string", default: "Contact"}
          - {label: "Body (Content)", name: "body", widget: "markdown"}

  # COLLECTION 3: Content types you can create new entries for.
  - name: "content_types"
    label: "Content"
    collapsed: false
    collections:
      - name: "posts"
        label: "Blog Posts"
        folder: "content/post/"
        create: true
        slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Publish Date", name: "date", widget: "datetime"}
          - {label: "Summary", name: "summary", widget: "text", required: false}
          - {label: "Tags", name: "tags", widget: "list", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "publications"
        label: "Publications"
        folder: "content/publication/"
        create: true
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Authors", name: "authors", widget: "list"}
          - {label: "Date", name: "date", widget: "datetime"}
          - {label: "Publication Venue", name: "publication", widget: "string", required: false}
          - {label: "Abstract", name: "abstract", widget: "markdown", required: false}
          - {label: "URL to PDF", name: "url_pdf", widget: "string", required: false}
          - {label: "URL to Code", name: "url_code", widget: "string", required: false}

  # COLLECTION 4: General site-wide settings.
  - name: "settings"
    label: "Site Configuration"
    collapsed: true
    files:
      - file: "config/_default/menus.yaml"
        label: "Navigation Menu"
        name: "menu"
        fields:
          - name: main
            label: Menu Items
            widget: list
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
              - {label: "Order (Weight)", name: "weight", widget: "number"}
      - file: "config/_default/params.yaml"
        label: "Theme & Site Parameters"
        name: "params"
        fields:
          - {label: "Theme", name: "theme", widget: "select", options: ["minimal", "classic", "ocean", "forest", "dark", "mr-robot", "custom"]}
          - {label: "Font", name: "font", widget: "select", options: ["default", "classic", "rose", "ocean"]}