backend:
  name: github
  repo: bhati-saa/bhati-saa.github.io # Or your actual repo
  branch: main
  auth_type: github # Already forced by JS, but good to have

media_folder: "static/uploads" # Simple path

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts_test" # Use a test folder
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}