backend:
  name: github
  repo: bhati-saa/bhati-saa.github.io
  branch: main # Or your default branch (e.g., master)
  # auth_type: implicit # Can be useful if you have issues with the default GitHub auth flow
  # site_domain: your_username.github.io # Usually not needed for basic GitHub auth

# This is used for the media library if you want to upload images via Decap CMS
media_folder: "static/media/uploads" # Path where uploaded files will be stored (relative to repo root)
public_folder: "/media/uploads"      # Path used in the src attribute for markdown (relative to site root)

# Local backend can be useful for testing Decap CMS locally before pushing.
# Only enable it when you run `npx decap-server` locally.
# local_backend: true

# Define your content types (collections)
collections:
  # --- Author Profile (content/authors/admin/_index.md) ---
  - name: "profile"
    label: "Author Profile (admin)"
    files:
      - label: "My Profile"
        name: "admin_profile"
        file: "content/authors/admin/_index.md"
        fields:
          - { label: "Title (Your Name)", name: "title", widget: "string" }
          - { label: "Role", name: "role", widget: "string", required: false }
          - { label: "Bio", name: "bio", widget: "markdown", required: false }
          - { label: "Interests", name: "interests", widget: "list", required: false }
          - { label: "Social Links", name: "social", widget: "list", fields: [
              { label: "Icon", name: "icon", widget: "string", hint: "e.g., envelope, twitter, github, linkedin. Font Awesome pack (e.g., 'fab' for brands)." },
              { label: "Icon Pack", name: "icon_pack", widget: "select", options: ["fas", "fab", "far", "ai"], default: "fas" },
              { label: "Link", name: "link", widget: "string" }
            ], required: false }
          - { label: "Organizations", name: "organizations", widget: "list", fields: [
              { label: "Name", name: "name", widget: "string" },
              { label: "URL", name: "url", widget: "string", required: false }
            ], required: false }
          - { label: "Education", name: "education", widget: "object", fields: [
              { label: "Courses", name: "courses", widget: "list", fields: [
                { label: "Course", name: "course", widget: "string" },
                { label: "Institution", name: "institution", widget: "string" },
                { label: "Year", name: "year", widget: "number" }
              ]}
            ], required: false }
          - { label: "Email", name: "email", widget: "string", required: false, hint: "Will be ROT13 encoded on the site" }
          # Add other profile fields you use: e.g., highlight_name, first_name, last_name, avatar (use image widget for avatar if you want to manage it here), etc.
          # If avatar is just a filename, use string. If you want to upload/select:
          - { label: "Avatar Filename", name: "avatar", widget: "string", default: "avatar.jpg", hint: "Image in this author's folder. Use image widget if you want to upload here.", required: false }
          - { label: "User Groups", name: "user_groups", widget: "list", required: false, hint: "e.g., Researchers, Admins" }
          - { label: "Superuser?", name: "superuser", widget: "boolean", default: true }

  # --- Homepage Sections (content/home/*.md) ---
  # This is a bit generic. You'll need to inspect each .md file in content/home/
  # to see its specific front matter and `widget` type.
  - name: "homepage_sections"
    label: "Homepage Sections"
    files:
      - label: "About / Biography"
        name: "about_widget"
        file: "content/home/about.md" # Check if this file exists and its structure
        fields:
          - { label: "Widget", name: "widget", widget: "hidden", default: "about" }
          - { label: "Enabled", name: "active", widget: "boolean", default: true }
          - { label: "Weight (Order)", name: "weight", widget: "number" }
          - { label: "Title", name: "title", widget: "string", required: false }
          - { label: "Author", name: "author", widget: "string", default: "admin", hint: "Username of author folder (usually 'admin')" }
          # Add other fields from your about.md front matter

      - label: "Skills"
        name: "skills_widget"
        file: "content/home/skills.md" # Check if this file exists and its structure
        fields:
          - { label: "Widget", name: "widget", widget: "hidden", default: "features" } # Or 'skills' if it's a dedicated skills widget
          - { label: "Enabled", name: "active", widget: "boolean", default: true }
          - { label: "Weight (Order)", name: "weight", widget: "number" }
          - { label: "Title", name: "title", widget: "string", default: "Skills" }
          - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
          - { label: "Items (Features)", name: "feature", widget: "list", fields: [
              {label: "Name", name: "name", widget: "string"},
              {label: "Description", name: "description", widget: "string", required: false},
              {label: "Icon", name: "icon", widget: "string"},
              {label: "Icon Pack", name: "icon_pack", widget: "select", options: ["fas", "fab", "ai"], default: "fas"},
              {label: "Percentage (for skill bar)", name: "percent", widget: "number", min: 0, max: 100, required: false}
            ]}

      - label: "Experience"
        name: "experience_widget"
        file: "content/home/experience.md"
        fields:
          - { label: "Widget", name: "widget", widget: "hidden", default: "experience" }
          - { label: "Enabled", name: "active", widget: "boolean", default: true }
          - { label: "Weight (Order)", name: "weight", widget: "number" }
          - { label: "Title", name: "title", widget: "string", default: "Experience" }
          - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
          - { label: "Date Format", name: "date_format", widget: "string", default: "Jan 2006" }
          - { label: "Items", name: "items", widget: "list", fields: [
              { label: "Title", name: "title", widget: "string" },
              { label: "Company", name: "company", widget: "string" },
              { label: "Company URL", name: "company_url", widget: "string", required: false },
              { label: "Company Logo (filename)", name: "company_logo", widget: "string", required: false },
              { label: "Location", name: "location", widget: "string", required: false },
              { label: "Date Start", name: "date_start", widget: "datetime", format: "YYYY-MM-DD" }, # Use datetime for easier picking
              { label: "Date End", name: "date_end", widget: "datetime", format: "YYYY-MM-DD", required: false, hint: "Leave blank for current" },
              { label: "Description", name: "description", widget: "markdown" }
            ]}

      # Add other homepage widgets like accomplishments, posts (hero feed), contact, etc.
      # Example: Contact
      - label: "Contact Widget"
        name: "contact_widget"
        file: "content/home/contact.md"
        fields:
          - { label: "Widget", name: "widget", widget: "hidden", default: "contact" }
          - { label: "Enabled", name: "active", widget: "boolean", default: true }
          - { label: "Weight (Order)", name: "weight", widget: "number" }
          - { label: "Title", name: "title", widget: "string", default: "Contact" }
          - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
          - { label: "Email", name: "email", widget: "string", required: false, hint: "Will be ROT13 encoded" }
          - { label: "Phone", name: "phone", widget: "string", required: false }
          - { label: "Address", name: "address", widget: "object", fields: [
              { label: "Street", name: "street", widget: "string", required: false },
              { label: "City", name: "city", widget: "string", required: false },
              { label: "Region", name: "region", widget: "string", required: false },
              { label: "Postcode", name: "postcode", widget: "string", required: false },
              { label: "Country", name: "country", widget: "string", required: false },
              { label: "Country Code", name: "country_code", widget: "string", required: false }
            ], required: false }
          - { label: "Coordinates", name: "coordinates", widget: "object", fields: [
              { label: "Latitude", name: "latitude", widget: "string" },
              { label: "Longitude", name: "longitude", widget: "string" }
            ], required: false }
          - { label: "Directions", name: "directions", widget: "string", required: false }
          - { label: "Office Hours", name: "office_hours", widget: "list", widgetDefault: [], required: false, fields: [
              { label: "Day and Time", name: "hours", widget: "string" }
            ]}
          # If using Netlify Forms or Formspree:
          # - { label: "Form Provider", name: "form", widget: "object", fields: [...] }


  # --- Blog Posts (content/post/*.md) ---
  - name: "posts"
    label: "Blog Posts"
    folder: "content/post"
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Summary", name: "summary", widget: "text", required: false }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Last Modified", name: "lastmod", widget: "datetime", required: false }
      - { label: "Publish Date (override)", name: "publishDate", widget: "datetime", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - { label: "Authors", name: "authors", widget: "list", default: ["admin"], hint: "List of author usernames (e.g., admin)" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Categories", name: "categories", widget: "list", required: false }
      - { label: "Featured Image", name: "featured", widget: "boolean", default: false }
      - { label: "Image", name: "image", widget: "object", fields: [
          { label: "Filename (or path from static/)", name: "filename", widget: "image", required: false, hint: "Upload or path like /media/my-image.jpg" },
          { label: "Caption", name: "caption", widget: "string", required: false },
          { label: "Focal Point", name: "focal_point", widget: "select", options: ["Smart", "Center", "TopLeft", "Top", "TopRight", "Left", "Right", "BottomLeft", "Bottom", "BottomRight"], default: "Smart", required: false },
          { label: "Preview Only", name: "preview_only", widget: "boolean", default: false }
        ], required: false }
      - { label: "Projects", name: "projects", widget: "list", required: false, hint: "Link to project folder names" }
      - { label: "Body", name: "body", widget: "markdown" }

  # --- Projects (content/project/*.md) ---
  - name: "projects"
    label: "Projects"
    folder: "content/project"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Summary", name: "summary", widget: "text", required: false }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "External Link", name: "external_link", widget: "string", required: false }
      - { label: "Image", name: "image", widget: "object", fields: [
          { label: "Filename (or path from static/)", name: "filename", widget: "image", required: false },
          { label: "Caption", name: "caption", widget: "string", required: false },
          { label: "Focal Point", name: "focal_point", widget: "select", options: ["Smart", "Center", "TopLeft", "Top", "TopRight", "Left", "Right", "BottomLeft", "Bottom", "BottomRight"], default: "Smart", required: false },
          { label: "Preview Only", name: "preview_only", widget: "boolean", default: false }
        ], required: false }
      - { label: "Body (Content)", name: "body", widget: "markdown" } # The content of the project page itself

  # --- Publications (content/publication/*.md) ---
  # Publications can be complex with BibTeX import. Decap CMS is better for manual entry/edits.
  - name: "publications"
    label: "Publications"
    folder: "content/publication"
    create: true
    slug: "{{slug}}" # Or perhaps a slug based on author-year
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Authors", name: "authors", widget: "list", default: ["admin"] }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD" } # Or "YYYY-MM-DDTHH:mm:ssZ" if time is important
      - { label: "Publication Type Code", name: "publication_types", widget: "list", field: {label: "Type Code", name: "type", widget: "select", options: ["0", "1", "2", "3", "4", "5", "6"], hint: "0=Uncategorized, 1=Conference, 2=Journal, 3=Preprint, 4=Report, 5=Book, 6=Book chapter"}}
      - { label: "Publication Name (e.g., Journal or Conference Name)", name: "publication", widget: "string", required: false }
      - { label: "Publication Short Name (e.g., J. ACM)", name: "publication_short", widget: "string", required: false }
      - { label: "Abstract", name: "abstract", widget: "markdown", required: false }
      - { label: "Summary", name: "summary", widget: "text", required: false } # Shorter than abstract
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - { label: "Projects", name: "projects", widget: "list", required: false, hint: "Link to project folder names" }
      - { label: "Image", name: "image", widget: "object", fields: [
          { label: "Filename (or path from static/)", name: "filename", widget: "image", required: false },
          { label: "Caption", name: "caption", widget: "string", required: false },
          { label: "Focal Point", name: "focal_point", widget: "select", options: ["Smart", "Center", "TopLeft", "Top", "TopRight", "Left", "Right", "BottomLeft", "Bottom", "BottomRight"], default: "Smart", required: false },
          { label: "Preview Only", name: "preview_only", widget: "boolean", default: false }
        ], required: false }
      - { label: "Links", name: "links", widget: "list", fields: [
          { label: "Name", name: "name", widget: "string", hint: "e.g., PDF, Code, Slides, Video" },
          { label: "URL", name: "url", widget: "string" },
          { label: "Icon Pack", name: "icon_pack", widget: "select", options: ["fas", "fab", "ai"], default: "fas" },
          { label: "Icon", name: "icon", widget: "string" }
        ], required: false }
      - { label: "URL PDF", name: "url_pdf", widget: "string", required: false }
      - { label: "URL Code", name: "url_code", widget: "string", required: false }
      # Add other publication specific fields like doi, url_dataset, url_poster, etc.

  # --- Site Configuration (config/_default/params.yaml or .toml) ---
  # This is more advanced and requires care. Hugo Blox often uses params.yaml
  - name: "site_settings"
    label: "Site Settings (params.yaml)"
    files:
      - label: "Theme Parameters"
        name: "params"
        file: "config/_default/params.yaml" # Or params.toml if you use TOML
        # This indicates that the file is YAML. Use `format: "toml"` for TOML.
        format: "yaml-frontmatter" # A bit of a hack for full YAML files, treat as frontmatter
        fields: # Define fields based on your params.yaml content
          - { label: "Theme", name: "theme", widget: "string" }
          - { label: "Font", name: "font", widget: "string", required: false }
          - { label: "Color Theme", name: "day_night", widget: "boolean", default: true }
          # Add more params here... e.g., contact_links, marketing, features, security, etc.
          # Example for a nested structure:
          - label: "Appearance"
            name: "appearance"
            widget: "object"
            fields:
              - { label: "Theme", name: "theme_default", widget: "string" }
              - { label: "Font", name: "font_default", widget: "string" }
              - { label: "Font Size", name: "font_size_default", widget: "string" }
          - label: "Marketing"
            name: "marketing"
            widget: "object"
            fields:
              - { label: "SEO Title", name: "seo_title", widget: "string" }
              - { label: "SEO Description", name: "seo_description", widget: "string" }
              # ... and so on
    # You could also add config/_default/config.yaml and menus.yaml if desired,
    # but be very careful editing core Hugo config files via CMS.